compute:

  # Add cloud configuration here.
  provider:
    credentials: XXXXXX           # Cloud key ID
    region: us-east-1             # Cloud region
    vendor: aws                   # Vendor, only aws

  # Training configuration.
  train:

    cpus: 1                       # Number of CPUs
    disk_size: 200                # Disk size
    gpus: 0                       # Number of GPUs
    instance: t2.xlarge           # AWS instance type
    memory: null                  # RAM memory
    nodes: 0                      # Nodes to start with
    scale_down_seconds: 1800      # Second in between every scaling down evaluation

    # Your environment variables
    environment:
      MY_ENVIRONMENT_VARIABLE: "example"

hyper_params:
  settings:
    strategy: random_search
    trials: 2
  params:
    learning_rate: uniform(0.001, 0.008, 20)
    gamma: 0.234